---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: environment
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/create-application-gateway.sh

params:
  AZURE_ENVIRONMENT:                                 ""
  AZURE_CLIENT_ID:                                   ""
  AZURE_CLIENT_SECRET:                               ""
  AZURE_TENANT_ID:                                   ""
  AZURE_APPLICATION_GATEWAY_NAME:                    ""
