---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: environment
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/tasks/delete-application-security-group.sh

params:
  AZURE_ENVIRONMENT:                                 ""
  AZURE_SUBSCRIPTION_ID:                             ""
  AZURE_CLIENT_ID:                                   ""
  AZURE_CLIENT_SECRET:                               ""
  AZURE_TENANT_ID:                                   ""
  AZURE_APPLICATION_SECURITY_GROUP_NAME:             ""
