---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: pipelines
  - name: director-config
  - name: bosh-cli
  - name: bosh-release
  - name: cpi-release
  - name: bosh-cpi-src
  - name: stemcell

outputs:
  - name: director-state

run:
  path: bosh-cpi-src/ci/tasks/deploy-director.sh
