---
platform: linux
image: docker:///boshcpi/azure-cpi-release
inputs:
- name: stemcell
- name: bosh-cpi-release
- name: bats
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
params:
  BASE_OS:                      replace-me
  AZURE_CLIENT_ID:              replace-me
  AZURE_CLIENT_SECRET:          replace-me
  AZURE_TENANT_ID:              replace-me
  AZURE_GROUP_NAME:             replace-me
  AZURE_GROUP_NAME_FOR_NETWORK: replace-me
  SSH_PRIVATE_KEY:              replace-me
  BAT_VCAP_PASSWORD:            replace-me
  BAT_SECOND_STATIC_IP:         replace-me
  BAT_NETWORK_STATIC_IP:        replace-me
  BAT_NETWORK_CIDR:             replace-me
  BAT_NETWORK_RESERVED_RANGE:   replace-me
  BAT_NETWORK_STATIC_RANGE:     replace-me
  BAT_NETWORK_GATEWAY:          replace-me
  AZURE_VNET_NAME_FOR_BATS:     replace-me
  AZURE_CF_SUBNET_NAME:         replace-me
  AZURE_DEFAULT_SECURITY_GROUP: replace-me
  BAT_DIRECTOR_PASSWORD:        replace-me

