---
platform: linux
image: docker:///abelhu/azure-cpi-release-test
inputs:
- name: bosh-cpi-release
- name: stemcell
run:
  path: bosh-cpi-release/ci/tasks/run-lifecycle.sh
params:
  AZURE_SUBSCRIPTION_ID:          replace-me
  AZURE_CLIENT_ID:                replace-me
  AZURE_CLIENT_SECRET:            replace-me
  AZURE_TENANT_ID:                replace-me
  AZURE_GROUP_NAME_FOR_VMS:       replace-me
  AZURE_GROUP_NAME_FOR_NETWORK:   replace-me
  AZURE_STORAGE_ACCOUNT_NAME:     replace-me
  AZURE_VNET_NAME_FOR_LIFECYCLE:  replace-me
  AZURE_BOSH_SUBNET_NAME:         replace-me
  AZURE_DEFAULT_SECURITY_GROUP:   replace-me
  SSH_PUBLIC_KEY:                 replace-me
