#!/usr/bin/env bash

set -e

source bosh-cpi-release/ci/tasks/utils.sh

check_param AZURE_SUBSCRIPTION_ID
check_param AZURE_CLIENT_ID
check_param AZURE_CLIENT_SECRET
check_param AZURE_TENANT_ID
check_param AZURE_GROUP_NAME_1
check_param AZURE_GROUP_NAME_2
check_param AZURE_PUBLIC_IP_1
check_param AZURE_PUBLIC_IP_2
check_param AZURE_STORAGE_ACCOUNT_NAME
check_param SSH_PUBLIC_KEY
check_param AZURE_VNET_NAME_FOR_LIFECYCLE
check_param AZURE_BOSH_SUBNET_NAME
check_param AZURE_DEFAULT_SECURITY_GROUP

export BOSH_AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
export BOSH_AZURE_TENANT_ID=${AZURE_TENANT_ID}
export BOSH_AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
export BOSH_AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
export BOSH_AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
export BOSH_AZURE_RESOURCE_GROUP_NAME_1=${AZURE_GROUP_NAME_1}
export BOSH_AZURE_RESOURCE_GROUP_NAME_2=${AZURE_GROUP_NAME_2}
export BOSH_AZURE_PUBLIC_IP_1=${AZURE_PUBLIC_IP_1}
export BOSH_AZURE_PUBLIC_IP_2=${AZURE_PUBLIC_IP_2}
export BOSH_AZURE_VNET_NAME=${AZURE_VNET_NAME_FOR_LIFECYCLE}
export BOSH_AZURE_SUBNET_NAME=${AZURE_BOSH_SUBNET_NAME}
export BOSH_AZURE_SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
export BOSH_AZURE_DEFAULT_SECURITY_GROUP=${AZURE_DEFAULT_SECURITY_GROUP}
export BOSH_AZURE_STEMCELL_ID="bosh-stemcell-00000000-0000-0000-0000-0AZURECPICI0"

source /etc/profile.d/chruby.sh
chruby 2.1.2

cd bosh-cpi-release/src/bosh_azure_cpi

bundle install
bundle exec rspec spec/integration
