---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/azure-cpi-release}

inputs:
  - name: environment
  - name: bosh-cpi-src
  - name: stemcell

outputs:
  - name: stemcell-state

run:
  path: bosh-cpi-src/ci/tasks/upload-stemcell.sh

params:
  AZURE_ENVIRONMENT:     ""
  AZURE_TENANT_ID:       ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_CLIENT_ID:       ""
  AZURE_CLIENT_SECRET:   ""
  IS_HEAVY_STEMCELL:     true
