---
groups:
  - name: bosh-azure-cpi-release
    jobs:
      - build-candidate
      - integration-unmanaged-disks
      - integration-managed-disks
      - integration-windows-unmanaged-disks
      - integration-windows-managed-disks
      - bats-unmanaged-disks
      - bats-managed-disks
      - promote-candidate

shared:
  - &azure-environment-params
    AZURE_ENVIRONMENT:                    {{azure_environment}}
    AZURE_TENANT_ID:                      {{azure_tenant_id}}
    AZURE_SUBSCRIPTION_ID:                {{azure_subscription_id}}
    AZURE_CLIENT_ID:                      {{azure_client_id}}
    AZURE_CLIENT_SECRET:                  {{azure_client_secret}}
    AZURE_CERTIFICATE:                    {{azure_certificate}}

  - &create-bats-environment
    put: environment
    params:
      delete_on_failure: true
      generate_random_name: true
      terraform_source: pipelines/azure/assets/terraform

  - &destroy-bats-environment
    put: environment
    params:
      action: destroy
      env_name_file: environment/name
      terraform_source: pipelines/azure/assets/terraform
    get_params:
      action: destroy

  - &prepare-director
    task: prepare-director
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     azure
      DIRECTOR_VARS_FILE: {{azure_director_vars_file}}

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml
    params: &run-bats-params
      INFRASTRUCTURE:                     azure
      STEMCELL_NAME:                      bosh-azure-hyperv-ubuntu-trusty-go_agent
      BAT_INFRASTRUCTURE:                 azure
      BAT_NETWORKING:                     manual
      BAT_RSPEC_FLAGS:                    "--tag ~raw_ephemeral_storage"

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml

  - &create-integration-environment
    put: environment
    params:
      delete_on_failure: true
      generate_random_name: true
      terraform_source: bosh-cpi-src/ci/assets/terraform/integration

  - &destroy-integration-environment
    put: environment
    params:
      action: destroy
      env_name_file: environment/name
      terraform_source: bosh-cpi-src/ci/assets/terraform/integration
    get_params:
      action: destroy

  - &run-integration
    task: run-integration
    file: bosh-cpi-src/ci/tasks/run-integration.yml
    params: &run-integration-params
      <<: *azure-environment-params
      SSH_PUBLIC_KEY:                                 {{ssh_public_key}}
      AZURE_APPLICATION_GATEWAY_NAME:                 {{azure_application_gateway_name}}
      AZURE_APPLICATION_SECURITY_GROUP_NAME:          {{azure_application_security_group_name}}
      AZURE_APPLICATION_SECURITY_GROUP_TESTS_ENABLED: {{azure_application_security_group_tests_enabled}}

  - &run-integration-windows
    task: run-integration-windows
    file: bosh-cpi-src/ci/tasks/run-integration-windows.yml
    params: &run-integration-windows-params
      <<: *run-integration-params

  - &create-application-gateway
    task: create-application-gateway
    file: bosh-cpi-src/ci/tasks/create-application-gateway.yml
    params:
      <<: *azure-environment-params
      AZURE_APPLICATION_GATEWAY_NAME: {{azure_application_gateway_name}}

  - &delete-application-gateway
    task: delete-application-gateway
    file: bosh-cpi-src/ci/tasks/delete-application-gateway.yml
    params:
      <<: *azure-environment-params
      AZURE_APPLICATION_GATEWAY_NAME: {{azure_application_gateway_name}}

  - &create-application-security-group
    task: create-application-security-group
    file: bosh-cpi-src/ci/tasks/create-application-security-group.yml
    params:
      <<: *azure-environment-params
      AZURE_LOCATION:                                 {{azure_location}}
      AZURE_APPLICATION_SECURITY_GROUP_NAME:          {{azure_application_security_group_name}}
      AZURE_APPLICATION_SECURITY_GROUP_TESTS_ENABLED: {{azure_application_security_group_tests_enabled}}

  - &delete-application-security-group
    task: delete-application-security-group
    file: bosh-cpi-src/ci/tasks/delete-application-security-group.yml
    params:
      <<: *azure-environment-params
      AZURE_APPLICATION_SECURITY_GROUP_NAME:          {{azure_application_security_group_name}}
      AZURE_APPLICATION_SECURITY_GROUP_TESTS_ENABLED: {{azure_application_security_group_tests_enabled}}

  - &ensure-cleanup
    task: ensure-cleanup
    file: bosh-cpi-src/ci/tasks/ensure-cleanup.yml
    params:
      <<: *azure-environment-params

  - &create-bats-standard-public-ip
    task: create-bats-standard-public-ip
    file: bosh-cpi-src/ci/tasks/create-bats-standard-public-ip.yml
    params:
      <<: *azure-environment-params
      AZURE_LOCATION:                        {{azure_location}}
      AZURE_BATS_STANDARD_PUBLIC_IP_NAME:    {{azure_bats_standard_public_ip_name}}

  - &delete-bats-standard-public-ip
    task: delete-bats-standard-public-ip
    file: bosh-cpi-src/ci/tasks/delete-bats-standard-public-ip.yml
    params:
      <<: *azure-environment-params
      AZURE_BATS_STANDARD_PUBLIC_IP_NAME:    {{azure_bats_standard_public_ip_name}}

  - &run-az-bats
    task: run-az-bats
    file: bosh-cpi-src/ci/tasks/run-az-bats.yml
    params: &run-az-bats-params
      INFRASTRUCTURE:                     azure
      STEMCELL_NAME:                      bosh-azure-hyperv-ubuntu-trusty-go_agent
      BAT_INFRASTRUCTURE:                 azure
      BAT_NETWORKING:                     manual
      BAT_RSPEC_FLAGS:                    "--tag ~raw_ephemeral_storage"
      AZURE_BATS_STANDARD_PUBLIC_IP_NAME: {{azure_bats_standard_public_ip_name}}
      AZURE_BATS_ZONE:                    {{azure_bats_zone}}

jobs:
  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}
        - {trigger: false, get: version-semver, params: {bump: patch}}
        - {trigger: false, get: bosh-cli}
      - put: version-semver
        params: {file: version-semver/number}
      - task: build
        file: bosh-cpi-src/ci/tasks/build-candidate.yml
      - put: bosh-cpi-dev-artifacts
        params: {file: candidate/*.tgz}

  - name: integration-unmanaged-disks
    serial: true
    plan:
      - aggregate:
        - {get: bosh-cpi-release, trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-cpi-src,     trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,         trigger: false, resource: azure-ubuntu-stemcell}
      - <<: *create-integration-environment
      - <<: *create-application-security-group
      - <<: *create-application-gateway
      - <<: *run-integration
        params:
          <<: *run-integration-params
          AZURE_USE_MANAGED_DISKS: false
      - do:
        - <<: *delete-application-gateway
        - <<: *delete-application-security-group
        - <<: *destroy-integration-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: integration-managed-disks
    serial: true
    plan:
      - aggregate:
        - {get: bosh-cpi-release, trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-cpi-src,     trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,         trigger: false, resource: azure-ubuntu-stemcell}
      - <<: *create-integration-environment
      - <<: *create-application-security-group
      - <<: *create-application-gateway
      - <<: *run-integration
        params:
          <<: *run-integration-params
          AZURE_USE_MANAGED_DISKS: true
      - do:
        - <<: *delete-application-gateway
        - <<: *delete-application-security-group
        - <<: *destroy-integration-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: integration-windows-unmanaged-disks
    serial: true
    plan:
      - aggregate:
        - {get: bosh-cpi-release, trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-cpi-src,     trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,         trigger: false, resource: azure-windows-stemcell}
      - <<: *create-integration-environment
      - <<: *create-application-security-group
      - <<: *create-application-gateway
      - <<: *run-integration-windows
        params:
          <<: *run-integration-windows-params
          AZURE_USE_MANAGED_DISKS: false
      - do:
        - <<: *delete-application-gateway
        - <<: *delete-application-security-group
        - <<: *destroy-integration-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: integration-windows-managed-disks
    serial: true
    plan:
      - aggregate:
        - {get: bosh-cpi-release, trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-cpi-src,     trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,         trigger: false, resource: azure-windows-stemcell}
      - <<: *create-integration-environment
      - <<: *create-application-security-group
      - <<: *create-application-gateway
      - <<: *run-integration-windows
        params:
          <<: *run-integration-windows-params
          AZURE_USE_MANAGED_DISKS: true
      - do:
        - <<: *delete-application-gateway
        - <<: *delete-application-security-group
        - <<: *destroy-integration-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: bats-unmanaged-disks
    serial: true
    plan:
      - aggregate:
        - {get: cpi-release,     trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-release,    trigger: false, resource: bosh-release}
        - {get: bosh-cpi-src,    trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,        trigger: false, resource: azure-ubuntu-stemcell}
        - {get: bosh-deployment, trigger: false}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
      - <<: *create-bats-environment
      - <<: *prepare-director
        params:
          <<: *prepare-director-params
          OPTIONAL_OPS_FILE: |
            -o pipelines/shared/assets/ops/remove-hm.yml
            -o bosh-deployment/external-ip-with-registry-not-recommended.yml
      - <<: *deploy-director
      - <<: *run-bats
      - do:
        - <<: *teardown
        - <<: *destroy-bats-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: bats-managed-disks
    serial: true
    plan:
      - aggregate:
        - {get: cpi-release,     trigger: true,  resource: bosh-cpi-dev-artifacts, passed: [build-candidate]}
        - {get: bosh-release,    trigger: false, resource: bosh-release}
        - {get: bosh-cpi-src,    trigger: false, resource: bosh-cpi-src-in,        passed: [build-candidate]}
        - {get: stemcell,        trigger: false, resource: azure-ubuntu-stemcell}
        - {get: bosh-deployment, trigger: false}
        - {get: pipelines,       trigger: false}
        - {get: bosh-cli,        trigger: false}
        - {get: bats,            trigger: false}
      - <<: *create-bats-environment
      - <<: *create-bats-standard-public-ip
      - <<: *prepare-director
        params:
          <<: *prepare-director-params
          OPTIONAL_OPS_FILE: |
            -o pipelines/shared/assets/ops/remove-hm.yml
            -o bosh-deployment/external-ip-with-registry-not-recommended.yml
            -o bosh-deployment/azure/use-managed-disks.yml
      - <<: *deploy-director
      - <<: *run-az-bats
      - do:
        - <<: *teardown
        - <<: *delete-bats-standard-public-ip
        - <<: *destroy-bats-environment
        ensure:
          do:
            - <<: *ensure-cleanup

  - name: promote-candidate
    plan:
      - aggregate:
        - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts, passed: [integration-unmanaged-disks, integration-managed-disks, integration-windows-unmanaged-disks, integration-windows-managed-disks, bats-unmanaged-disks, bats-managed-disks]}
        - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-out}
        - {trigger: false, get: release-version-semver, params: {bump: major}}
        - {trigger: false, get: bosh-cli}
      - task: promote
        file: bosh-cpi-src/ci/tasks/promote-candidate.yml
        params:
          S3_ACCESS_KEY_ID:     {{s3_access_key__promote}}
          S3_SECRET_ACCESS_KEY: {{s3_secret_key__promote}}
      - put: bosh-cpi-src
        resource: bosh-cpi-src-out
        params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}
      - put: release-version-semver
        params: {file: release-version-semver/number}

resource_types:
  - name: terraform_type
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource

resources:
  - name: bosh-cpi-dev-artifacts
    type: s3
    source:
      regexp: bosh-azure-cpi-(\d+\.\d+\.\d+)\.tgz
      bucket: {{s3_azure_cpi_pipeline_bucket}}
      region_name: {{s3_region__primary}}
      access_key_id: {{s3_access_key__primary}}
      secret_access_key: {{s3_secret_key__primary}}
  - name: bosh-cpi-src-in
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-azure-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-azure-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml
  - name: bosh-cpi-src-out
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/bosh-azure-cpi-release.git
      branch: master
      private_key: {{github_deployment_key__bosh-azure-cpi-release}}
  - name: version-semver
    type: semver
    source:
      key:               current-version # dev-release version
      bucket:            {{s3_azure_cpi_pipeline_bucket}}
      access_key_id:     {{s3_access_key__primary}}
      secret_access_key: {{s3_secret_key__primary}}
  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_azure_cpi_pipeline_bucket}}
      access_key_id:     {{s3_access_key__primary}}
      secret_access_key: {{s3_secret_key__primary}}
  - name: environment
    type: terraform_type
    source:
      storage:
        access_key_id:     {{s3_access_key__primary}}
        secret_access_key: {{s3_secret_key__primary}}
        bucket:            {{terraform_bucket}}
        bucket_path:       terraform-state
      vars:
        location:              {{azure_location}}
        azure_environment:     {{azure_environment}}
        azure_subscription_id: {{azure_subscription_id}}
        azure_client_id:       {{azure_client_id}}
        azure_client_secret:   {{azure_client_secret}}
        azure_tenant_id:       {{azure_tenant_id}}
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: azure-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-azure-hyperv-ubuntu-trusty-go_agent
  - name: azure-windows-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-azure-hyperv-windows2012R2-go_agent
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gocli-bats
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
