---
groups:
  - name: bosh-azure-cpi-release
    jobs:
      - recreate-infrastructure-primary
      - build-candidate
      - integration-unmanaged-disks
      - integration-managed-disks
      - integration-windows-unmanaged-disks
      - integration-windows-managed-disks
      - bats-unmanaged-disks
      - bats-managed-disks
      - promote-candidate

shared:
  - &azure-environment-params
    AZURE_ENVIRONMENT:                    {{azure_environment}}
    AZURE_SUBSCRIPTION_ID:                {{azure_subscription_id}}
    AZURE_CLIENT_ID:                      {{azure_client_id}}
    AZURE_CLIENT_SECRET:                  {{azure_client_secret}}
    AZURE_TENANT_ID:                      {{azure_tenant_id}}

  - &prepare-director
    task: prepare-director
    file: bosh-cpi-src/ci/tasks/prepare-director.yml
    params: &prepare-director-params
      <<: *azure-environment-params
      AZURE_VNET_NAME_FOR_BATS:           {{azure_vnet_name_for_bats}}
      AZURE_BOSH_SUBNET_NAME:             {{azure_bosh_subnet_name}}
      AZURE_DEFAULT_SECURITY_GROUP:       {{azure_default_security_group}}
      OPTIONAL_OPS_FILE: |
        -o pipelines/shared/assets/ops/remove-hm.yml
        -o bosh-deployment/external-ip-with-registry-not-recommended.yml
        -o bosh-cpi-src/ci/assets/ops/use-additional-resource-group.yml

  - &deploy-director
    task: deploy-director
    file: bosh-cpi-src/ci/tasks/deploy-director.yml

  - &run-bats
    task: run-bats
    file: bosh-cpi-src/ci/tasks/run-bats.yml
    params: &run-bats-params
      <<: *azure-environment-params
      AZURE_DEFAULT_SECURITY_GROUP:       {{azure_default_security_group}}
      AZURE_VNET_NAME_FOR_BATS:           {{azure_vnet_name_for_bats}}
      BATS_FIRST_NETWORK:
        name:                             {{azure_cf_subnet_name}}
        static_ip_1:                      {{bat_network_static_ip}}
        static_ip_2:                      {{bat_second_static_ip}}
        cidr:                             {{bat_network_cidr}}
        reserved_range:                   {{bat_network_reserved_range}}
        static_range:                     {{bat_network_static_range}}
        gateway:                          {{bat_network_gateway}}
      BATS_SECOND_NETWORK:
        name:                             {{azure_cf_second_subnet_name}}
        static_ip_1:                      {{bat_second_network_static_ip}}
        cidr:                             {{bat_second_network_cidr}}
        reserved_range:                   {{bat_second_network_reserved_range}}
        static_range:                     {{bat_second_network_static_range}}
        gateway:                          {{bat_second_network_gateway}}
      STEMCELL_NAME:                      bosh-azure-hyperv-ubuntu-trusty-go_agent
      BAT_INFRASTRUCTURE:                 azure
      BAT_NETWORKING:                     manual
      BAT_RSPEC_FLAGS:                    "--tag ~raw_ephemeral_storage"

  - &teardown
    task: teardown
    file: bosh-cpi-src/ci/tasks/teardown.yml

  - &run-integration
    task: run-integration
    file: bosh-cpi-src/ci/tasks/run-integration.yml
    params: &run-integration-params
      <<: *azure-environment-params
      AZURE_VNET_NAME_FOR_INTEGRATION:    {{azure_vnet_name_for_integration}}
      AZURE_BOSH_SUBNET_NAME:             {{azure_bosh_subnet_name}}
      AZURE_BOSH_SECOND_SUBNET_NAME:      {{azure_bosh_second_subnet_name}}
      AZURE_DEFAULT_SECURITY_GROUP:       {{azure_default_security_group}}
      SSH_PUBLIC_KEY:                     {{ssh_public_key}}
      AZURE_APPLICATION_GATEWAY_NAME:     {{azure_application_gateway_name}}

  - &run-integration-windows
    task: run-integration-windows
    file: bosh-cpi-src/ci/tasks/run-integration-windows.yml

jobs:
- name: recreate-infrastructure-primary
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}

  - task: azure-provision
    file: bosh-cpi-src/ci/tasks/azure-provision.yml
    params:
      <<: *azure-environment-params
      AZURE_DEFAULT_GROUP_NAME:                          {{azure_default_group_name}}
      AZURE_ADDITIONAL_GROUP_NAME:                       {{azure_additional_group_name}}
      AZURE_DEFAULT_GROUP_NAME_MANAGED_DISKS:            {{azure_default_group_name_managed_disks}}
      AZURE_ADDITIONAL_GROUP_NAME_MANAGED_DISKS:         {{azure_additional_group_name_managed_disks}}
      AZURE_DEFAULT_GROUP_NAME_WINDOWS:                  {{azure_default_group_name_windows}}
      AZURE_ADDITIONAL_GROUP_NAME_WINDOWS:               {{azure_additional_group_name_windows}}
      AZURE_DEFAULT_GROUP_NAME_WINDOWS_MANAGED_DISKS:    {{azure_default_group_name_windows_managed_disks}}
      AZURE_ADDITIONAL_GROUP_NAME_WINDOWS_MANAGED_DISKS: {{azure_additional_group_name_windows_managed_disks}}
      AZURE_REGION_NAME:                                 {{azure_region_name}}
      AZURE_VNET_NAME_FOR_BATS:                          {{azure_vnet_name_for_bats}}
      AZURE_VNET_NAME_FOR_INTEGRATION:                   {{azure_vnet_name_for_integration}}
      AZURE_REGION_SHORT_NAME:                           {{azure_region_short_name}}
      AZURE_STORAGE_ACCOUNT_NAME:                        {{azure_storage_account_name}}
      AZURE_STORAGE_ACCOUNT_NAME_MANAGED_DISKS:          {{azure_storage_account_name_managed_disks}}
      AZURE_STORAGE_ACCOUNT_NAME_WINDOWS:                {{azure_storage_account_name_windows}}
      AZURE_STORAGE_ACCOUNT_NAME_WINDOWS_MANAGED_DISKS:  {{azure_storage_account_name_windows_managed_disks}}
      AZURE_BOSH_SUBNET_NAME:                            {{azure_bosh_subnet_name}}
      AZURE_BOSH_SECOND_SUBNET_NAME:                     {{azure_bosh_second_subnet_name}}
      AZURE_CF_SUBNET_NAME:                              {{azure_cf_subnet_name}}
      AZURE_CF_SECOND_SUBNET_NAME:                       {{azure_cf_second_subnet_name}}
      AZURE_APPLICATION_GATEWAY_NAME:                    {{azure_application_gateway_name}}

- name: build-candidate
  serial: true
  plan:
    - aggregate:
      - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-in}
      - {trigger: false, get: version-semver, params: {bump: patch}}
      - {trigger: false, get: bosh-cli}
    - put: version-semver
      params: {file: version-semver/number}
    - task: build
      file: bosh-cpi-src/ci/tasks/build-candidate.yml
    - put: bosh-cpi-dev-artifacts
      params: {file: candidate/*.tgz}

- name: integration-unmanaged-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: stemcell, resource: azure-ubuntu-stemcell}
  - <<: *run-integration
    params:
      <<: *run-integration-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name}}
      AZURE_STORAGE_ACCOUNT_NAME:     {{azure_storage_account_name}}
      AZURE_USE_MANAGED_DISKS:        false

- name: integration-managed-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: stemcell, resource: azure-ubuntu-stemcell}
  - <<: *run-integration
    params:
      <<: *run-integration-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name_managed_disks}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name_managed_disks}}
      AZURE_STORAGE_ACCOUNT_NAME:     {{azure_storage_account_name_managed_disks}}
      AZURE_USE_MANAGED_DISKS:        true

- name: integration-windows-unmanaged-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: stemcell, resource: azure-windows-stemcell}
  - <<: *run-integration-windows
    params:
      <<: *run-integration-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name_windows}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name_windows}}
      AZURE_STORAGE_ACCOUNT_NAME:     {{azure_storage_account_name_windows}}
      AZURE_USE_MANAGED_DISKS:        false

- name: integration-windows-managed-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: bosh-cpi-dev-artifacts}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: stemcell, resource: azure-windows-stemcell}
  - <<: *run-integration-windows
    params:
      <<: *run-integration-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name_windows_managed_disks}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name_windows_managed_disks}}
      AZURE_STORAGE_ACCOUNT_NAME:     {{azure_storage_account_name_windows_managed_disks}}
      AZURE_USE_MANAGED_DISKS:        true

- name: bats-unmanaged-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: cpi-release,  resource: bosh-cpi-dev-artifacts}
    - {trigger: false,                            get: stemcell,     resource: azure-ubuntu-stemcell}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: bats}
    - {trigger: false,                            get: bosh-cli}
    - {trigger: false,                            get: bosh-release}
    - {trigger: false,                            get: bosh-deployment}
    - {trigger: false,                            get: pipelines}
  - <<: *prepare-director
    params:
      <<: *prepare-director-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name}}
      AZURE_USE_MANAGED_DISKS:        false
      AZURE_STORAGE_ACCOUNT_NAME:     {{azure_storage_account_name}}
  - do:
      - <<: *deploy-director
      - <<: *run-bats
        params:
          <<: *run-bats-params
          AZURE_GROUP_NAME:           {{azure_additional_group_name}}
    ensure:
      do:
        - <<: *teardown

- name: bats-managed-disks
  serial: true
  plan:
  - aggregate:
    - {trigger: true,  passed: [build-candidate], get: cpi-release,  resource: bosh-cpi-dev-artifacts}
    - {trigger: false,                            get: stemcell,     resource: azure-ubuntu-stemcell}
    - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, resource: bosh-cpi-src-in}
    - {trigger: false,                            get: bats}
    - {trigger: false,                            get: bosh-cli}
    - {trigger: false,                            get: bosh-release}
    - {trigger: false,                            get: bosh-deployment}
    - {trigger: false,                            get: pipelines}
  - <<: *prepare-director
    params:
      <<: *prepare-director-params
      AZURE_DEFAULT_GROUP_NAME:       {{azure_default_group_name_managed_disks}}
      AZURE_ADDITIONAL_GROUP_NAME:    {{azure_additional_group_name_managed_disks}}
      AZURE_USE_MANAGED_DISKS:        true
  - do:
      - <<: *deploy-director
      - <<: *run-bats
        params:
          <<: *run-bats-params
          AZURE_GROUP_NAME:           {{azure_additional_group_name_managed_disks}}
    ensure:
      do:
        - <<: *teardown

- name: promote-candidate
  plan:
  - aggregate:
    - {trigger: false, get: bosh-cpi-release, resource: bosh-cpi-dev-artifacts, passed: [integration-unmanaged-disks, integration-managed-disks, integration-windows-unmanaged-disks, integration-windows-managed-disks, bats-unmanaged-disks, bats-managed-disks]}
    - {trigger: false, get: bosh-cpi-src, resource: bosh-cpi-src-out}
    - {trigger: false, get: release-version-semver, params: {bump: major}}

  - task: promote
    file: bosh-cpi-src/ci/tasks/promote-candidate.yml
    params:
      S3_ACCESS_KEY_ID:     {{s3_access_key__promote}}
      S3_SECRET_ACCESS_KEY: {{s3_secret_key__promote}}

  - put: bosh-cpi-src
    resource: bosh-cpi-src-out
    params: {repository: promoted/repo, rebase: true, tag_prefix: "v", tag: promoted/integer_version}

  - put: release-version-semver
    params: {file: release-version-semver/number}

resources:
- name: bosh-cpi-dev-artifacts
  type: s3
  source:
    regexp: bosh-azure-cpi-(\d+\.\d+\.\d+)\.tgz
    bucket: {{s3_azure_cpi_pipeline_bucket}}
    region_name: {{s3_region__primary}}
    access_key_id: {{s3_access_key__primary}}
    secret_access_key: {{s3_secret_key__primary}}
- name: bosh-cpi-src-in
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-azure-cpi-release.git
    branch: master
    private_key: {{github_deployment_key__bosh-azure-cpi-release}}
    ignore_paths:
      - .final_builds/**/*.yml
      - releases/**/*.yml
- name: bosh-cpi-src-out
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/bosh-azure-cpi-release.git
    branch: master
    private_key: {{github_deployment_key__bosh-azure-cpi-release}}
- name: version-semver
  type: semver
  source:
    key:               current-version # dev-release version
    bucket:            {{s3_azure_cpi_pipeline_bucket}}
    access_key_id:     {{s3_access_key__primary}}
    secret_access_key: {{s3_secret_key__primary}}
- name: release-version-semver
  type: semver
  source:
    key:               release-current-version
    bucket:            {{s3_azure_cpi_pipeline_bucket}}
    access_key_id:     {{s3_access_key__primary}}
    secret_access_key: {{s3_secret_key__primary}}
- name: bosh-cli
  type: s3
  source:
    regexp: bosh-cli-([0-9.]+)-linux-amd64
    bucket: bosh-cli-artifacts
    region_name: us-east-1
- name: pipelines
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
    branch: master
- name: bosh-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/bosh
- name: azure-ubuntu-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-ubuntu-trusty-go_agent
- name: azure-windows-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-azure-hyperv-windows2012R2-go_agent
- name: bats
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
    branch: gocli-bats
- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master
